#!/bin/bash
~/.config/X11/xinitrc &
bsw_monitors bootstrap
nm-applet &
nitrogen --restore 2> /dev/null
picom &
urxvtd &
run_dunst &

bspc config focused_border_color    "#74838c"
bspc config normal_border_color     "#2E3440"
bspc config border_width            1
bspc config window_gap              12
bspc config focus_follows_pointer   true
bspc config top_padding             26
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

bspc rule -a calendar.google.com__calendar desktop='office' follow=on
bspc rule -a Slack desktop='office' follow=on
bspc rule -a TelegramDesktop desktop='office' follow=on
bspc rule -a code-oss desktop='code' follow=on
bspc rule -a Thunar desktop='files' follow=on
bspc rule -a Terminator desktop='term' follow=on
bspc rule -a Mysql-workbench-bin desktop='db' follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Nitrogen state=floating follow=on

floating_noborder
